### ISSUE TITLE
Crash with Xaero's minimap 1.16.3

### ISSUE THREAD

**Issue by walbuuk** [user11681/limitless#14]
Causes client to crash when I load both limitless and Xaero's minimap regular version. Works fine without Xaero's.
Minecraft 1.16.3
Attached crash log.

[crash-2020-10-14_17.26.06-client.txt](https://github.com/user11681/limitless/files/5378899/crash-2020-10-14_17.26.06-client.txt)

**Comment by user11681** [comment]
Xaero's Minimap is difficult to debug because it is closed-source. I will not work on this issue unless xaero96 should make the source of Xaero's Minimap public.
