### ISSUE TITLE
Limitless is Incompatible with Sodium

### ISSUE THREAD

**Issue by matty45** [user11681/limitless#17]
No idea what is causing these two mods to behave badly.

Here is the full log of the crash: https://paste.ee/p/5NJt5

**Comment by user11681** [comment]
That does not look like a Sodium incompatibility to me. I suspect that this problem is related to the JVM. :thinking:

**Comment by user11681** [comment]
Could you try updating to Java 8u261?

**Comment by matty45** [comment]
Nada, same error i think. 
https://paste.ee/p/6siOg

**Comment by user11681** [comment]
I was able to reproduce this bug with Oracle and GraalVM Java 8 and without any other mods. Looks like I didn't do enough testing.

**Comment by matty45** [comment]
Hopefully it should be quick/easy to fix.
