### ISSUE TITLE
Incompatibility with Aquarius

### ISSUE THREAD

**Issue by Setadokalo** [user11681/limitless#28]
Putting a trident into the enchantment table with both Aquarius and limitless installed causes the (internal, untested in multiplayer) server to freeze entirely - as far as I've seen the server doesn't actually crash, but it locks up and leaving the world fully softlocks the game, requiring a restart.

**Comment by user11681** [comment]
limitless assumes constant enchantment power only when maximum level is 1 and Aquarius increases the maximum level of Channeling without increasing the required enchantment power, so its maximum level should have been increased from 3 to 2^31 - 1. Decreasing the maximum level of Channeling to 3 in limitless' configuration should fix the problem for until I should patch this bug.
