### ISSUE TITLE
random crash when starting up

### ISSUE THREAD

**Issue by ChunkyRagu89** [user11681/limitless#30]
limitless is preventing minecraft from starting up for some reason, although it loads completely fine without limitless
ive only got jumploader, limitless and the fabric api (all updated) installed, heres the log: https://pastebin.com/MubTWtcv

**Comment by user11681** [comment]
I have released version 1.1.1. Could you test it and report back?

**Comment by Gamersdissent1337** [comment]
Same problem here no matter how I work my mod order with Fabric API, Phosphor, Modloader, Sodium, and Lithium it crashes on startup. Pastebin https://pastebin.com/AMJuGeA8

**Comment by user11681** [comment]
That link is invalid.

**Comment by user11681** [comment]
I have released version 1.1.2 and confirmed that it works without issues on my end.

**Comment by HGrewal20** [comment]
I may have found the problem, if you are using a custom version of Java under the "Java Executable" input like me.
You are going to run into problems ONLY IF you use the OPENJ9 versions. However, the mod seems to work well with the HOTSPOT versions:
![java_e_pic](https://user-images.githubusercontent.com/66027592/104768023-fda37600-573a-11eb-8db2-4a200b275cf7.png) .

**Comment by user11681** [comment]
The issue with Xaero's Minimap has been fixed recently.
I tested OpenJ9 8.0.275 and it appears to work as expected:
![Screenshot_20210115_234947](https://user-images.githubusercontent.com/44427720/104789247-5bac7980-578c-11eb-8c01-5869ca4009fa.png)

**Comment by ChunkyRagu89** [comment]
sorry for not responding for a few days, but yes the mods latest version (1.1.2) works. not sure what you guys have been talking about recently so im not sure if i should close this or if this is a completely different problem and should stay open...

**Comment by user11681** [comment]
If the original problem has been resolved, then this issue has served its purpose. Any other problems should be reported in separate issues.
