### ISSUE TITLE
Conflict with FairEnchanting in new versions - Minecraft 1.16.4

### ISSUE THREAD

**Issue by Sl-L** [user11681/limitless#31]
Minecraft Version: 1.16.4
FairEnchanting Version: 1.2.0
Limitless Version: 1.1.0

Error seems to be here, since its the only error that doesn't happen while just using one mod instead of both and its adove the "Error Starting" messages:
```
Cliente> [22:16:31] [main/WARN]: @Redirect conflict. Skipping limitless.mixins.json:anvil.AnvilScreenHandlerMixin->@Redirect::normalizeCost(Lnet/minecraft/class_1657;I)V with priority -1000, already redirected by fairenchanting.mixins.json:MixinAnvilScreenHandler->@Redirect::addExperienceLevels(Lnet/minecraft/class_1657;I)V with priority 1000
```

I know that, if this is the thing that causes the error, it's probably that is impossible have both mods together, but I still gonna post this because it was possible in older versions, I'm not saying this in a bad way.
PS: I'm also submiting this on FairEnchanting's issues.

**Comment by user11681** [comment]
limitless includes the same feature as FairEnchanting.

**Comment by Sl-L** [comment]
So I don't need to use FairEnchanting, and should just close this issue, right?

**Comment by Sl-L** [comment]
Thanks for the help, and sorry for the misunderstanding.
