### ISSUE TITLE
Incompatible with AnvilFix

### ISSUE THREAD

**Issue by UpcraftLP** [user11681/limitless#32]
as the title states, this mod is incompatible with AnvilFix, due to a [conflicting mixin](https://github.com/OnyxStudios/AnvilFix/blob/1fcea4237a1cbef668bd61cb3bdfaf33cfd60a68/src/main/java/io/github/onyxstudios/anvilfix/mixin/client/MixinAnvilScreen.java).

related crash report: https://paste.ubuntu.com/p/2fS3zNSjqk/

**Comment by user11681** [comment]
limitless seems to do what Anvil Fix does, so the user would be advised to use one and not use the other. One day I should do something about this monolith of a mod.
