### ISSUE TITLE
Crash when launching.

### ISSUE THREAD

**Issue by ArrowFX** [user11681/limitless#43]
Here is the full log: 
[latest.log](https://github.com/user11681/limitless/files/6765058/latest.log)

Feel free to ask any other questions you might have.

**Comment by user11681** [comment]
limitless already does what Tax Free Levels does; so there is a conflict.

**Comment by ArrowFX** [comment]
> 
> 
> limitless already does what Tax Free Levels does; so there is a conflict.

Thanks for the info :D
