### ISSUE TITLE
Will limitless be updated to be compatible with 1.17

### ISSUE THREAD

**Issue by RaXorX** [user11681/limitless#45]
https://github.com/user11681/limitless/issues/44
Currently the 1.3.4 version works only with 1.17.1. Are there plans to make it compatible with 1.17?

EDIT: Well seems like the version markup is not so accurate. 1.3.2 works with 1.17 while 1.3.4 works only with 1.17.1 not with 1.17. Please could you correct the info on the modpage?

**Comment by user11681** [comment]
It is correct. CurseForge omits the last version component on the main page.
![Screenshot_20210717_171850](https://user-images.githubusercontent.com/44427720/126045321-8a97488e-8014-42ea-99c8-1241a5e6db95.png)
![Screenshot_20210717_171925](https://user-images.githubusercontent.com/44427720/126043286-63eb7ae2-8794-439e-b61d-16fa8f674449.png)
