### ISSUE TITLE
[0.4.3] Singleplayer freezes on load

### ISSUE THREAD

**Issue by Thaumatarge** [user11681/limitless#5]
No idea what is causing it as there is no error log, or crash log, simply the game freezing the moment a world loads.

It may be an incompatibility with my massive amount of mods, but if that would be so, I have no clue which mod could potentially cause it... Would there potentially be a conflict with Better Enchanted Books? It changes how the enchantments are sorted in the tool tip.

**Comment by user11681** [comment]
I suppose that this is a mod incompatibility, considering that it workks without issues for me. I will look at and test with Better Enchanted Books. Meanwhile, it would be useful if you could pinpoint the combinations of mods that produces this bug.

**Comment by user11681** [comment]
Not an issue with Better Enchanted Books. `latest.log` probably would provide some useful information.

**Comment by Thaumatarge** [comment]
Will post one ASAP

**Comment by Thaumatarge** [comment]
This is very strange... Uh... It is a memory issue? (My game has 6GB allocated)
[latest.log](https://github.com/user11681/limitless/files/5212810/latest.log)
![image](https://user-images.githubusercontent.com/34694089/92997534-4e4c5d80-f514-11ea-9b51-caaf9c830398.png)

**Comment by Thaumatarge** [comment]
I figured it out! As it seems, REI tries to load pretty much ALL the possible enchantments and enchantment levels because of the changes done to how they are handled, thus causing a massive memory leak.
