### ISSUE TITLE
"enchant_randomly" Function enchants items with too high of level

### ISSUE THREAD

**Issue by Thaumatarge** [user11681/limitless#6]
I have no idea how this one can be fixed, but it seems when a loot table uses the "enchant_randomly" function, it causes the item to literally be enchanted randomly, giving it an enchantment of a level anywhere as high as it can be. Is this intentional?

**Comment by Thaumatarge** [comment]
![image](https://user-images.githubusercontent.com/34694089/92999483-78584c80-f521-11ea-8833-3cab6b9bb602.png)
Giving myself loot of abandoned mineshafts generates books such as this one.

**Comment by user11681** [comment]
Currently, it is generated by `MathHelper.nextInt(random, enchantment.getMinLevel(), enchantment.getMaxLevel())`. With what should I replace it? :thinking:

**Comment by Thaumatarge** [comment]
Is there a way to link it to the max enchantment shown in the Creative menu?

**Comment by Thaumatarge** [comment]
If not, then perhaps make it so that it caps off at 5, as in if maxLevel > 5 then 5

**Comment by Thaumatarge** [comment]
I can't think of any enchantment that goes above level 5 in vanilla

**Comment by user11681** [comment]
> Is there a way to link it to the max enchantment shown in the Creative menu?
Of course. I usually do not make such changes without keeping a backup.
