### ISSUE TITLE
Incompatible with mo'enchantments mod

### ISSUE THREAD

**Issue by SpyritMC** [user11681/limitless#7]
updating from version 1.3.0 to 1.4.3 causes the game to crash whenever i open and put an item into the enchantment table, it completely breaks the game and crashes.

**Comment by user11681** [comment]
I need a log to be able to determine the problem.

**Comment by SpyritMC** [comment]
[latest.log](https://github.com/user11681/limitless/files/5250554/latest.log)

**Comment by user11681** [comment]
It looks alright to me. Was this log generated after you put an item in an enchanting table? Also, if you have a crash report, then that would be preferable.

**Comment by SpyritMC** [comment]
it never left a crash report, i also realised it isnt because i put an item into the enchanting table. because when i went onto the world again this morning, i was just climbing a ladder, and tried to open a chest when i got to the top, it wouldnt open and animals were also frozen.

**Comment by user11681** [comment]
Minecraft most likely is attempting to calculate a suitable enchantment level for enchantments from More Enchantments. I might just make the default maximum level 1000 and make it configurable for every enchantment. (The latter feature is already implemented locally.)

**Comment by user11681** [comment]
Never mind. There is a better method of fixing this by keeping the default limit of 2^31 - 1.
